"""update enum

Revision ID: e725f55f6b43
Revises: 7564384a1f6c
Create Date: 2022-07-31 22:14:49.401381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e725f55f6b43'
down_revision = '7564384a1f6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
